apiVersion: v1
kind: Namespace
metadata:
  name: ice-kube-ns

-----
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: ice-kube
  namespace: ice-kube-ns
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: ice-kube
        spec:
          serviceAccountName: sa-default-token
          containers:
            - args:
                - suspend
              image: docker.com/keikoproj/ice-kube:latest
              imagePullPolicy: Always
              name: ice-kube
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 3
  suspend: false

-----
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deployment-reader
rules:
  - apiGroups:
      - extensions
      - apps
    resources:
      - deployments
      - replicasets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

-----
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-deployment
  # namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - apiGroup: ''
    kind: ServiceAccount
    name: sa-default-token
    namespace: ice-kube-ns

-----
apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  name: sa-default-token
